update@20240813

diff --git a/einat-ebpf/files/einat.init b/einat-ebpf/files/einat.init
--- a/einat-ebpf/files/einat.init
+++ b/einat-ebpf/files/einat.init
@@ -72,16 +72,16 @@ einat_instance() {
 	procd_open_data
 	# configure firewall
 	json_add_array firewall
-		# IPv4 input (This is not required if the upper-level gateway is Full Cone NAT)
-		json_add_object ''
-		json_add_string type rule
-		json_add_string target 'ACCEPT'
-		json_add_string name "Relax input limits"
-		json_add_string family 'ipv4'
-		json_add_string proto 'tcp udp'
-		json_add_string src "$(fw4 -q device $ifname)"
-		json_add_string dest_port "$ports"
-		json_close_object
+		# IPv4 input (Optional. Relax the localhost firewall)
+		#json_add_object ''
+		#json_add_string type rule
+		#json_add_string target 'ACCEPT'
+		#json_add_string name "Relax input limits"
+		#json_add_string family 'ipv4'
+		#json_add_string proto 'tcp udp'
+		#json_add_string src "$(fw4 -q device $ifname)"
+		#json_add_string dest_port "$ports"
+		#json_close_object
 		# IPv4 accept forward wan -> lan
 		json_add_object ''
 		json_add_string type rule
@@ -121,7 +121,8 @@ launcher() {
 		10) network_get_device wanifname "$DEF_WAN6";;
 		11) network_get_device wanifname "$DEF_WAN6";;
 	esac
-	[ -z "${ifname:=$wanifname}" ] && >&2 echo "$(basename $0): section $1 option ifname parsing failed, there may be no network connection" && let error++
+	local ifname="${ifname:-$wanifname}"
+	[ -z "$ifname" ] && >&2 echo "$(basename $0): section $1 option ifname parsing failed, there may be no network connection" && let error++
 
 	# review
 	[ -n "$EINAT_DEBUG" ] && {
diff --git a/natmapt/files/natmap.init b/natmapt/files/natmap.init
--- a/natmapt/files/natmap.init
+++ b/natmapt/files/natmap.init
@@ -1,4 +1,4 @@
-#!/bin/sh /etc/rc.common
+#!/bin/bash /etc/rc.common
 
 . "${IPKG_INSTROOT}/lib/functions/network.sh"
 
@@ -62,7 +62,7 @@ load_interfaces() {
 	local bind_ifname enable
 
 	config_get bind_ifname "$1" bind_ifname
-	config_get enable "$1" enable 0
+	config_get_bool enable "$1" enable 0
 
 	[ "$enable" = 1 ] && interfaces=" $(uci -q show network|grep "device='$bind_ifname'"|cut -f2 -d'.') $interfaces"
 }
@@ -72,9 +72,12 @@ define_global() {
 	[ "$2" == "0" ] || { >&2 echo "$(basename $0): section $1 validation failed"; return 1; }
 
 	local error=0
-	local v ucivv="enable def_tcp_stun def_udp_stun def_http_server def_tcp_interval def_udp_interval"
+	local v ucivv="enable def_tcp_stun def_udp_stun def_http_server def_fwmark_value def_tcp_interval def_udp_interval"
 	for v in $ucivv; do
-		[ -z "$(config_get $1 $v)" ] && err_msg__empty $1 $v && let error++
+		[ -z "$(config_get $1 $v)" ] && grep -qEv "^(def_fwmark_value)$" <<< "$v" && {
+			err_msg__empty $1 $v
+			let error++
+		}
 		config_get GLOBAL_$v $1 $v
 	done
 
@@ -87,6 +90,7 @@ validate_section_global() {
 		'def_tcp_stun:string' \
 		'def_udp_stun:string' \
 		'def_http_server:string' \
+		'def_fwmark_value:string' \
 		'def_tcp_interval:and(uinteger, min(1)):30' \
 		'def_udp_interval:and(uinteger, min(1)):15' \
 		'test_port:and(port, min(1))'
@@ -98,6 +102,7 @@ validate_section_natmap() {
 		'interval:and(uinteger, min(1))' \
 		'stun_server:string' \
 		'http_server:string' \
+		'fwmark_value:string' \
 		'comment:string' \
 		'udp_mode:bool:0' \
 		'family:or("ipv4", "ipv6"):ipv4' \
@@ -106,6 +111,7 @@ validate_section_natmap() {
 		'forward:bool:0' \
 		'forward_mode:or("dnat", "via"):via' \
 		'natloopback:bool:1' \
+		'forward_timeout:and(uinteger, min(1))' \
 		'forward_target:ipaddr(1)' \
 		'forward_port:port' \
 		'refresh:bool:0' \
@@ -156,6 +162,11 @@ fe80:(:[[:xdigit:]]{0,4}){0,4}%\w+|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|2[0-4]\
 	esac
 }
 
+# fwmark_match <fwmark>
+fwmark_match() {
+	echo "$1" | grep -E '^(0|0x[[:xdigit:]]+|[1-9][0-9]*|0[0-7]+)$'
+}
+
 natmap_instance() {
 
 	procd_open_instance "$1"
@@ -163,6 +174,7 @@ natmap_instance() {
 		${interval:+-k "$interval"} \
 		${stun_server:+-s "$stun_server"} \
 		${http_server:+-h "$http_server"} \
+		${fwmark_value:+-f "$fwmark_value"} \
 		${port:+-b "$port"} \
 
 	[ "${family}" = ipv4 ] && procd_append_param command -4
@@ -179,7 +191,9 @@ natmap_instance() {
 		network_get_device ifname "$DEF_WAN6" && procd_append_param netdev "$ifname"
 	}
 
-	[ "$forward" = 1 -a "$forward_mode" = "via" -a -n "${forward_target}" ] && procd_append_param command -t "$forward_target" -p "$forward_port"
+	if [ "$forward" = 1 -a "$forward_mode" = "via" -a -n "${forward_target}" ]; then
+		procd_append_param command ${forward_timeout:+-T "$forward_timeout"} -t "$forward_target" -p "$forward_port"
+	fi
 
 	procd_set_param env "SECTIONID=$1"
 	procd_append_param env "COMMENT=$comment"
@@ -277,8 +291,19 @@ natmap_instance() {
 }
 
 clear_status_files() {
+	local f sid="$1"
+
 	mkdir -p "${STATUS_PATH}" 2>/dev/null
-	find "${STATUS_PATH}" -type f -print0 | xargs -0 rm -f --
+	pushd "${STATUS_PATH}" >/dev/null
+	if [ -n "$sid" ]; then
+		for f in *.json; do
+			[ "$(jsonfilter -q -i $f -e '@.sid')" = "$sid" ] || continue
+			rm -f $f; break
+		done
+	else
+		find * -type f -print0 | xargs -0 rm -f --
+	fi
+	popd >/dev/null
 }
 
 # err_msg__empty <section> <option>
@@ -291,10 +316,13 @@ launcher() {
 	[ "$enable" = 0 ] && return 0
 
 	# global options
-	[ "$udp_mode" = 1 ] \
-		&& echo ${stun_server:=$GLOBAL_def_udp_stun} ${interval:=$GLOBAL_def_udp_interval} >/dev/null \
-		|| echo ${stun_server:=$GLOBAL_def_tcp_stun} ${interval:=$GLOBAL_def_tcp_interval} >/dev/null
-	echo ${http_server:=$GLOBAL_def_http_server} >/dev/null
+	if [ "$udp_mode" = 1 ]; then
+		local stun_server=${stun_server:-$GLOBAL_def_udp_stun} interval=${interval:-$GLOBAL_def_udp_interval}
+	else
+		local stun_server=${stun_server:-$GLOBAL_def_tcp_stun} interval=${interval:-$GLOBAL_def_tcp_interval}
+	fi
+	local http_server=${http_server:-$GLOBAL_def_http_server}
+	local fwmark_value=${fwmark_value:-$GLOBAL_def_fwmark_value}
 	# natmap options
 	local error=0
 	local proto ifname bind_ip lan_addr
@@ -303,7 +331,8 @@ launcher() {
 		ipv4) network_get_device ifname "$DEF_WAN";;
 		ipv6) network_get_device ifname "$DEF_WAN6";;
 	esac
-	[ -z "${bind_ifname:=$ifname}" ] && >&2 echo "$(basename $0): section $1 option bind_ifname parsing failed, there may be no $family network connection" && let error++
+	local bind_ifname=${bind_ifname:-$ifname}
+	[ -z "$bind_ifname" ] && >&2 echo "$(basename $0): section $1 option bind_ifname parsing failed, there may be no $family network connection" && let error++
 	case "$family" in
 		ipv4)
 			eval "bind_ip=\"\${NIC_${bind_ifname//[[:punct:]]/_}%/*}\""
@@ -314,15 +343,16 @@ launcher() {
 			lan_addr="${NIC6_br_lan%/*}"
 		;;
 	esac
-	[ -z "$bind_ip" ] && >&2 echo "$(basename $0): section $1 bind_ip parsing failed, there may be no $family network connection" && let error++
+	[ -z "$bind_ip" ] && >&2 echo "$(basename $0): section $1 option bind_ip parsing failed, there may be no $family network connection" && let error++
 	[ -z "$port" ] && err_msg__empty $1 port && let error++
+	[ -z "$fwmark_value" -o -n "$(fwmark_match "$fwmark_value")" ] || { >&2 echo "$(basename $0): section $1 option fwmark_value '$fwmark_value' is invalid"; let error++; }
 	## forward
 	if   [ "$forward" = 1 ]; then
 		[ "$forward_mode" = "dnat" -a "$family" = "ipv6" ] && >&2 echo "$(basename $0): section $1 option forward_mode 'dnat' not support under IPv6" && let error++
 		[ "$forward_mode" != "dnat" ] && natloopback=0
 		if [ -n "$forward_target" ]; then
-			[ -n "$(echo $forward_target|grep -E "^127(\.\d+){3}")" -o "$forward_target" = "::1" ] && forward_target="$lan_addr"
-			[ -n "$(echo $forward_target|grep -E "^0(\.\d+){3}")" -o "$forward_target" = "::" ] && forward_target="$bind_ip"
+			[ -n "$(grep -E "^127(\.\d+){3}" <<< $forward_target)" -o "$forward_target" = "::1" ] && forward_target="$lan_addr"
+			[ -n "$(grep -E "^0(\.\d+){3}"   <<< $forward_target)" -o "$forward_target" = "::" ] && forward_target="$bind_ip"
 			if [ -n "$forward_target" ]; then
 				[ -z "$(ip_match "$family" "$forward_target")" ] && >&2 echo "$(basename $0): section $1 option forward_target '$forward_target' not a $family address" && let error++
 			else
@@ -350,13 +380,13 @@ launcher() {
 		[ -x "$ddns_script" ] || { >&2 echo "$(basename $0): section $1 option ddns_script '$ddns_script' is empty or non-executable"; let error++; }
 		if [ -n "$ddns_srv" ]; then
 			[ -z "$ddns_srv_serv" ] && err_msg__empty $1 ddns_srv_serv && let error++
-			echo ${ddns_srv_target:=$ddns_srv} >/dev/null
+			local ddns_srv_target=${ddns_srv_target:-$ddns_srv}
 		fi
 	fi
 
 	# review
 	[ -n "$NATMAP_DEBUG" ] && {
-		local v ucivv="enable interval stun_server http_server comment udp_mode proto family bind_ifname ifname bind_ip lan_addr port forward forward_mode natloopback forward_target forward_port refresh clt_script clt_scheme clt_web_port clt_username clt_password notify_enable notify_script notify_tokens notify_custom_domain notify_text ddns_enable ddns_script ddns_tokens ddns_a ddns_aaaa ddns_srv ddns_srv_serv ddns_srv_proto ddns_srv_target ddns_srv_priority ddns_srv_weight ddns_https ddns_https_target ddns_https_svcparams ddns_https_priority custom_script"
+		local v ucivv="enable interval stun_server http_server fwmark_value comment udp_mode proto family bind_ifname ifname bind_ip lan_addr port forward forward_mode natloopback forward_timeout forward_target forward_port refresh clt_script clt_scheme clt_web_port clt_username clt_password notify_enable notify_script notify_tokens notify_custom_domain notify_text ddns_enable ddns_script ddns_tokens ddns_a ddns_aaaa ddns_srv ddns_srv_serv ddns_srv_proto ddns_srv_target ddns_srv_priority ddns_srv_weight ddns_https ddns_https_target ddns_https_svcparams ddns_https_priority custom_script"
 		for v in $ucivv; do eval "echo $1 $v=\'\$$v\'"; done # ash not support ${!v}
 	}
 	[ "$error" -gt 0 ] && return 1
@@ -397,6 +427,7 @@ start_service() {
 	[ "${GLOBAL_enable:=0}" == "0" ] && return 1
 
 	if [ -n "$sid" ]; then
+		clear_status_files "$sid"
 		validate_section_natmap "$sid" launcher
 	else
 		clear_status_files
@@ -404,14 +435,16 @@ start_service() {
 	fi
 }
 
+stop_service() {
+	local sid="$1"
+	clear_status_files "$sid"
+}
+
 reload_service() {
-	stop
-	start
+	stop "$@"
+	start "$@"
 }
 
 service_started() { procd_set_config_changed firewall; }
 
-service_stopped() {
-	clear_status_files
-	procd_set_config_changed firewall
-}
+service_stopped() { procd_set_config_changed firewall; }
